name: Run-Tests

on: [pull_request]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}



    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .
        pip install .[dev]

    - name: Run tests
      run: |
        python -m unittest discover
      env:
        CONN_STRING: sqlite+pysqlite:///test_db.db

    - name: Upload screenshot on error
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: selenium-error-screenshot
        path: *.png